---
include:
  - board: nice_nano//zmk
    shield: corne_left nice_view_adapter nice_view
    snippet: zmk-usb-logging
  # Lado derecho: trackball PMW3610 sin display.
  - board: nice_nano//zmk
    shield: corne_right
    snippet: zmk-usb-logging
